// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: allocator.proto

package allocator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeliveryAgent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId                 int32 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	CurrentLocationPincode int32 `protobuf:"varint,2,opt,name=CurrentLocationPincode,proto3" json:"CurrentLocationPincode,omitempty"`
}

func (x *DeliveryAgent) Reset() {
	*x = DeliveryAgent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_allocator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeliveryAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryAgent) ProtoMessage() {}

func (x *DeliveryAgent) ProtoReflect() protoreflect.Message {
	mi := &file_allocator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryAgent.ProtoReflect.Descriptor instead.
func (*DeliveryAgent) Descriptor() ([]byte, []int) {
	return file_allocator_proto_rawDescGZIP(), []int{0}
}

func (x *DeliveryAgent) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeliveryAgent) GetCurrentLocationPincode() int32 {
	if x != nil {
		return x.CurrentLocationPincode
	}
	return 0
}

type AllocatorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeliveryLocationPincode int32 `protobuf:"varint,1,opt,name=deliveryLocationPincode,proto3" json:"deliveryLocationPincode,omitempty"`
}

func (x *AllocatorRequest) Reset() {
	*x = AllocatorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_allocator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllocatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocatorRequest) ProtoMessage() {}

func (x *AllocatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_allocator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocatorRequest.ProtoReflect.Descriptor instead.
func (*AllocatorRequest) Descriptor() ([]byte, []int) {
	return file_allocator_proto_rawDescGZIP(), []int{1}
}

func (x *AllocatorRequest) GetDeliveryLocationPincode() int32 {
	if x != nil {
		return x.DeliveryLocationPincode
	}
	return 0
}

type AllocatorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeliveryAgent *DeliveryAgent `protobuf:"bytes,1,opt,name=deliveryAgent,proto3" json:"deliveryAgent,omitempty"`
}

func (x *AllocatorResponse) Reset() {
	*x = AllocatorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_allocator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllocatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocatorResponse) ProtoMessage() {}

func (x *AllocatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_allocator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocatorResponse.ProtoReflect.Descriptor instead.
func (*AllocatorResponse) Descriptor() ([]byte, []int) {
	return file_allocator_proto_rawDescGZIP(), []int{2}
}

func (x *AllocatorResponse) GetDeliveryAgent() *DeliveryAgent {
	if x != nil {
		return x.DeliveryAgent
	}
	return nil
}

var File_allocator_proto protoreflect.FileDescriptor

var file_allocator_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x16, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x5f, 0x0a, 0x0d, 0x44, 0x65, 0x6c,
	0x69, 0x76, 0x65, 0x72, 0x79, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x36, 0x0a, 0x16, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x69, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x16, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x50, 0x69, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x4c, 0x0a, 0x10, 0x41, 0x6c,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38,
	0x0a, 0x17, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x50, 0x69, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x17, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x50, 0x69, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x60, 0x0a, 0x11, 0x41, 0x6c, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a,
	0x0d, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x65,
	0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x0d, 0x64, 0x65, 0x6c,
	0x69, 0x76, 0x65, 0x72, 0x79, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x32, 0x80, 0x01, 0x0a, 0x1d, 0x44,
	0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x41, 0x6c, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5f, 0x0a, 0x08,
	0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x12, 0x28, 0x2e, 0x64, 0x65, 0x6c, 0x69, 0x76,
	0x65, 0x72, 0x79, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x6f,
	0x72, 0x2e, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x29, 0x2e, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x41, 0x6c, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1e, 0x5a,
	0x1c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x69, 0x6d, 0x61,
	0x39, 0x37, 0x31, 0x2f, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_allocator_proto_rawDescOnce sync.Once
	file_allocator_proto_rawDescData = file_allocator_proto_rawDesc
)

func file_allocator_proto_rawDescGZIP() []byte {
	file_allocator_proto_rawDescOnce.Do(func() {
		file_allocator_proto_rawDescData = protoimpl.X.CompressGZIP(file_allocator_proto_rawDescData)
	})
	return file_allocator_proto_rawDescData
}

var file_allocator_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_allocator_proto_goTypes = []interface{}{
	(*DeliveryAgent)(nil),     // 0: deliveryAgentAllocator.DeliveryAgent
	(*AllocatorRequest)(nil),  // 1: deliveryAgentAllocator.AllocatorRequest
	(*AllocatorResponse)(nil), // 2: deliveryAgentAllocator.AllocatorResponse
}
var file_allocator_proto_depIdxs = []int32{
	0, // 0: deliveryAgentAllocator.AllocatorResponse.deliveryAgent:type_name -> deliveryAgentAllocator.DeliveryAgent
	1, // 1: deliveryAgentAllocator.DeliveryAgentAllocatorService.allocate:input_type -> deliveryAgentAllocator.AllocatorRequest
	2, // 2: deliveryAgentAllocator.DeliveryAgentAllocatorService.allocate:output_type -> deliveryAgentAllocator.AllocatorResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_allocator_proto_init() }
func file_allocator_proto_init() {
	if File_allocator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_allocator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeliveryAgent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_allocator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllocatorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_allocator_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllocatorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_allocator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_allocator_proto_goTypes,
		DependencyIndexes: file_allocator_proto_depIdxs,
		MessageInfos:      file_allocator_proto_msgTypes,
	}.Build()
	File_allocator_proto = out.File
	file_allocator_proto_rawDesc = nil
	file_allocator_proto_goTypes = nil
	file_allocator_proto_depIdxs = nil
}
